import os
import sys
import uuid
import time
import json
from termcolor import colored

# Force UTF-8 for Windows compatibility if termcolor/print fails
sys.stdout.reconfigure(encoding='utf-8')
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from fastapi.testclient import TestClient
from app.main import app
from app.routing.deberta_classifier import get_semantic_classifier

client = TestClient(app)

print("\n" + "="*60)
print(colored(">>> DEBERTA ROUTER E2E TEST SUITE", "cyan", attrs=["bold"]))
print("="*60 + "\n")

# ---------------------------------------------------------
# TEST 1: DeBERTa Offline Router Loading
# ---------------------------------------------------------
print(colored("[TEST 1] Verifying DeBERTa Offline Loading...", "yellow", attrs=["bold"]))
try:
    classifier = get_semantic_classifier()
    if classifier.classifier is None:
        print(colored("[FAILED] DeBERTa model is not loaded correctly. Check 'models/deberta-router' folder.", "red"))
        sys.exit(1)
    print(colored("[PASS] DeBERTa classifier successfully loaded into memory.", "green"))
    
    # Quick sanity check on offline classification
    cat, conf, comp = classifier.classify_with_complexity("How do I write a fast inverse square root in C++?")
    print(rf"   -> Offline analysis yielded: {cat} (Confidence: {conf:.2f}, Complexity: {comp})")
    if cat == "CODE":
        print(colored("[PASS] Classifier accurately identified CODE.", "green"))
    else:
        print(colored(f"[WARN] Classifier expected CODE but got {cat}.", "yellow"))
except Exception as e:
    print(colored(f"[FAILED] Exception in DeBERTa loading: {e}", "red"))


# ---------------------------------------------------------
# TEST 2: The Vault Cache Flow
# ---------------------------------------------------------
print(colored("\n[TEST 2] Verifying Semantic Cache Workflow...", "yellow", attrs=["bold"]))
test_user = f"e2e_tester_{uuid.uuid4().hex[:6]}"
unique_prompt = f"What is the airspeed velocity of an unladen swallow? (ID: {uuid.uuid4().hex[:8]})"

try:
    # First Request (Should be Cache Miss & Generation)
    t0 = time.time()
    resp1 = client.post("/ask", json={
        "user_id": test_user,
        "prompt": unique_prompt,
        "user_tier": 2
    })
    t1 = time.time()
    data1 = resp1.json()
    
    if data1.get("source") != "AI_GENERATION":
        print(colored(f"[FAILED] First request should be AI_GENERATION but was {data1.get('source')}", "red"))
    else:
         print(colored(f"[PASS] First request hit AI generation cleanly (Time: {t1-t0:.2f}s)", "green"))

    # Second Request (Should be Cache Hit)
    t2 = time.time()
    resp2 = client.post("/ask", json={
        "user_id": test_user,
        "prompt": unique_prompt,
        "user_tier": 2
    })
    t3 = time.time()
    data2 = resp2.json()
    
    if data2.get("source") != "VAULT_CACHE":
        print(colored(f"[FAILED] Second request should be VAULT_CACHE but was {data2.get('source')}", "red"))
    else:
        cost_saved = data2.get("data", {}).get("metrics", {}).get("original_tokens", "N/A")
        print(colored(f"[PASS] Second request served from Cache for $0.00! (Time: {t3-t2:.4f}s)", "green"))
except Exception as e:
    print(colored(f"[FAILED] Exception in VAULT flow: {e}", "red"))


# ---------------------------------------------------------
# TEST 3: Feedback & Bandit Logic
# ---------------------------------------------------------
print(colored("\n[TEST 3] Verifying Feedback Loop (Thompson Sampling)...", "yellow", attrs=["bold"]))
try:
    # Provide Explicit Thumbs Up (+1.0)
    vault_id = data1.get("vault_id")
    if not vault_id:
        # Fallback if vault_id is not exposed in the API return structure reliably
        print(colored("[WARN] 'vault_id' was not returned by /ask endpoint. Skipping live DB feedback.", "yellow"))
    else:
        fb_resp = client.post("/feedback", json={
            "vault_id": vault_id,
            "feedback": 1.0,
            "comments": "Great answer generated by DeBERTa-routed model!"
        })
        if fb_resp.status_code == 200:
            print(colored(f"[PASS] User feedback recorded successfully in DB and Bandit updated.", "green"))
        else:
            print(colored(f"[FAILED] Feedback endpoint returned {fb_resp.status_code}: {fb_resp.text}", "red"))
except Exception as e:
    print(colored(f"[FAILED] Exception in Feedback flow: {e}", "red"))

print("\n" + "="*60)
print(colored(">>> ALL TESTS EXECUTED.", "cyan", attrs=["bold"]))
print("="*60 + "\n")
